In [1]:
import numpy as np
from hmmlearn import hmm
import csv


In [2]:
hmm_states = 2

model = hmm.CategoricalHMM(n_components=hmm_states)
model.emissionprob_ = np.array([[0.1,0.9],[0.9,0.1]])
model.transmat_ = np.array([[0.9,0.1],[0.1,0.9]])
model.startprob_ = np.array([0.8,0.2])
data,states = model.sample(n_samples = 1000,random_state=28)
data = np.squeeze(data)

In [29]:
print(states)

[0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0
 0 1 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 1 1 1 

In [4]:

# constant n_obs
# n_obs = 1000
# # Set p(H) apriori for simulation as a biased coin.
# p_h = 0.8

# # Model experiment as a single biased coin flipped 1000 times.
# data = np.random.binomial(1, p_h, n_obs=n_obs)

In [130]:
n_states = 2
n_features = 2
n_obs = data.shape[0]
# emission = np.random.rand(n_obs,n_states)
# emission = emission/np.tile(np.expand_dims(np.sum(emission,axis=1),axis=1),(1,2))

emission = np.random.rand(n_states,n_features)
emission = emission/np.tile(np.expand_dims(np.sum(emission,axis=1),axis=1),(1,2))
# emission = np.array([[0.5,0.5],[0.5,0.5]])

transition =  np.random.rand(n_states,n_states)
transition = transition/np.tile(np.expand_dims(np.sum(transition,axis=1),axis=1),(1,2))
transition = np.array([[0.76,0.24],[0.2,0.8]])


forward = np.random.rand(n_obs,n_states)
scale_factors = np.zeros((n_obs))
forward_hat = np.zeros((n_obs,n_states))

backward = np.random.rand(n_obs,n_states)
backward_hat = np.zeros((n_obs,n_states))

init_prob = np.array([0.5,0.5])


p_old = -10000
tol = 0.0001
max_iter = 10

mu = np.random.rand(n_states)

In [131]:
print(f'emission is {emission} and transition is {transition}')

emission is [[0.60368982 0.39631018]
 [0.82567216 0.17432784]] and transition is [[0.76 0.24]
 [0.2  0.8 ]]


In [132]:
for ite in range(max_iter):
    forward[0,:] = init_prob * emission[:,data[0]]
    scale_factors[0] = np.sum(forward[0,:])
    forward_hat[0,:] = forward[0,:]/scale_factors[0]
    
    for t in range(n_obs-1):
        temp = np.matmul(forward_hat[t,:] ,np.transpose(transition)) * emission[:,data[t+1]]
        scale_factors[t+1] = np.sum(temp)
        forward_hat[t+1,:] = temp/scale_factors[t+1]
        # print(f'temp is {temp} and the scale factor is {scale_factors[t+1]} and the forward_hat is {forward_hat[t+1]}')

        forward[t+1,:] = forward_hat[t+1,:]*np.prod(scale_factors[0:t+1])

    backward[-1,:] = 1
    backward_hat[-1,:] = backward[-1,:]
    for t in reversed(range(n_obs-1)):
        temp = np.matmul(backward_hat[t+1,:]*emission[:,data[t+1]],transition)
        backward_hat[t,:] = temp/scale_factors[t+1]
        backward[t,:] = backward_hat[t,:]*np.prod(scale_factors[t+1:-1])


    a = np.zeros((n_obs,n_states))
    b = np.zeros((n_obs,n_states,n_states))
    for i in range(n_obs):
        for j in range(n_states):
            a[i,j] = forward_hat[i,j]*backward_hat[i,j]
    for t in range(n_obs-1):
        for i in range(n_states):
            for j in range(n_states):
                b[t,i,j] = scale_factors[t+1]*forward_hat[t,i]*backward_hat[t+1,j]*transition[i,j]*emission[j,data[t+1]]

    for i in range(n_states):
        for j in range(n_states):
            transition[i,j] = np.sum(b[0:-1,i,j])/np.sum(b[0:-1,i,:])
            # print(np.sum(b[0:-1,i,j]),np.sum(b[0:-1,i,:]))

    for i in range(n_states):
        init_prob[i] = a[0,i]/np.sum(a[0,:])

    for i in range(n_states):
        for j in range(n_states):
            emission[j,i] = np.sum(a[np.argwhere(data==i),j]) / np.sum(a[:,j])
            
    p = np.sum(np.log(scale_factors))
    print(f'p is:{p},transition is {transition}')
    # print(f'transition prob is: {transition}')
    # print(f'emission prob is:{emission}')
    if p>p_old and p - p_old < tol:
        break
    p_old = p

p is:-768.9427548163993,transition is [[0.73005689 0.26994311]
 [0.15229384 0.84770616]]
p is:-638.9995894859331,transition is [[0.73713128 0.26286872]
 [0.07270504 0.92729496]]
p is:-598.1261411699029,transition is [[0.78140559 0.21859441]
 [0.02091353 0.97908647]]
p is:-599.6960880483696,transition is [[0.75316346 0.24683654]
 [0.00396405 0.99603595]]
p is:-653.6271627974492,transition is [[4.01968463e-01 5.98031537e-01]
 [5.11937013e-04 9.99488063e-01]]
p is:-839.7719869831195,transition is [[1.76298998e-02 9.82370100e-01]
 [1.13724770e-05 9.99988628e-01]]
p is:-716.9145355505955,transition is [[2.91136749e-05 9.99970886e-01]
 [3.62928571e-09 9.99999996e-01]]
p is:-691.9514207518048,transition is [[4.91736006e-08 9.99999951e-01]
 [1.29327305e-12 1.00000000e+00]]
p is:-691.9309038354177,transition is [[8.32286082e-11 1.00000000e+00]
 [4.60178723e-16 1.00000000e+00]]
p is:-691.9309038653856,transition is [[1.40868280e-13 1.00000000e+00]
 [1.63743016e-19 1.00000000e+00]]


In [127]:
print(b[0:-1,1,1])

[2.27307924 0.25773233 0.25773233 0.25773233 0.25773233 0.02748279
 2.27307924 0.02748279 0.24238543 0.24238543 0.24238543 2.27307924
 0.02748279 0.24238543 2.27307924 0.25773233 0.25773233 0.25773233
 0.25773233 0.25773233 0.25773233 0.02748279 2.27307924 0.25773233
 0.25773233 0.25773233 0.02748279 0.24238543 0.24238543 0.24238543
 0.24238543 0.24238543 0.24238543 0.24238543 0.24238543 0.24238543
 2.27307924 0.25773233 0.25773233 0.25773233 0.25773233 0.25773233
 0.25773233 0.25773233 0.25773233 0.25773233 0.25773233 0.25773233
 0.25773233 0.25773233 0.02748279 2.27307924 0.25773233 0.25773233
 0.25773233 0.25773233 0.25773233 0.25773233 0.25773233 0.25773233
 0.25773233 0.25773233 0.25773233 0.25773233 0.25773233 0.25773233
 0.25773233 0.25773233 0.25773233 0.25773233 0.25773233 0.25773233
 0.25773233 0.02748279 2.27307924 0.25773233 0.25773233 0.25773233
 0.25773233 0.25773233 0.02748279 0.24238543 0.24238543 0.24238543
 2.27307924 0.25773233 0.25773233 0.25773233 0.02748279 0.2423

In [128]:
transition

array([[9.69894213e-14, 1.00000000e+00],
       [9.76588765e-20, 1.00000000e+00]])

In [123]:
emission

array([[0.25860591, 0.74139409],
       [0.94555583, 0.05444417]])

In [30]:
# model = hmm.CategoricalHMM(n_components=n_states,emissionprob_prior=emission,transmat_prior=transition,startprob_prior=init_prob)
model2 = hmm.CategoricalHMM(n_components=n_states,n_iter=1000)


In [31]:
model2.fit(data.reshape(-1,1))
hidden_states = model2.predict(data.reshape(-1,1))
print("Most likely hidden states:", hidden_states)


Most likely hidden states: [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0
 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 

In [40]:
model2.monitor_.converged


True

In [33]:
model2.emissionprob_

array([[0.08646279, 0.91353721],
       [0.87767051, 0.12232949]])

In [34]:
model2.transmat_

array([[0.88572501, 0.11427499],
       [0.10842401, 0.89157599]])