In [1]:
import numpy as np
from hmmlearn import hmm


In [2]:
hmm_states = 2

model = hmm.CategoricalHMM(n_components=hmm_states)
model.emissionprob_ = np.array([[0.4,0.6],[0.3,0.7]])
model.transmat_ = np.array([[0.2,0.8],[0.1,0.9]])
model.startprob_ = np.array([0.4,0.6])
data,states = model.sample(n_samples = 1000,random_state=28)
data = np.squeeze(data)

In [3]:
model2 = hmm.CategoricalHMM(n_components=hmm_states,n_iter=1000,random_state=30,implementation='scaling')
model2.fit(data.reshape(-1,1))
hidden_states = model2.predict(data.reshape(-1,1))
# print("Most likely hidden states:", hidden_states)


In [4]:
model2.emissionprob_

array([[0.30638483, 0.69361517],
       [0.49639247, 0.50360753]])

In [5]:
model2.transmat_

array([[0.96217209, 0.03782791],
       [0.90664536, 0.09335464]])

In [6]:
model2.startprob_

array([0.93568289, 0.06431711])

In [7]:
model2.monitor_.history

deque([-838.023677543698,
       -622.3735648783038,
       -622.3452903116571,
       -622.3230925715274,
       -622.3060586902734,
       -622.2932136870318,
       -622.2836530193379])